import {
  ALL_CATEGORY_KEY,
  SUBSCRIPTION_CATEGORIES,
} from "../constants/subscriptionCategories";
import type { LanguageCode } from "../types/settings";
import type { BillingCycle, BillingCycleValue } from "../types/subscription";

export { ALL_CATEGORY_KEY };

export const categoryDisplayOrder = SUBSCRIPTION_CATEGORIES;

const localizedCategoryLabels = {
  en: {
    [ALL_CATEGORY_KEY]: "All",
    ai: "AI",
    creative: "Creative",
    learning: "Learning",
    music: "Music",
    other: "Other",
    sns: "SNS",
    video: "Video",
  },
  ja: {
    [ALL_CATEGORY_KEY]: "すべて",
    ai: "AI",
    creative: "制作",
    learning: "学習",
    music: "音楽",
    other: "その他",
    sns: "SNS",
    video: "動画",
  },
  ko: {
    [ALL_CATEGORY_KEY]: "전체",
    ai: "AI",
    creative: "제작",
    learning: "학습",
    music: "음악",
    other: "기타",
    sns: "SNS",
    video: "영상",
  },
  zh: {
    [ALL_CATEGORY_KEY]: "全部",
    ai: "AI",
    creative: "创作",
    learning: "学习",
    music: "音乐",
    other: "其他",
    sns: "SNS",
    video: "视频",
  },
} as const satisfies Record<LanguageCode, Record<string, string>>;

export function getCategoryLabel(
  category: string,
  language: LanguageCode,
): string {
  if (!category.trim()) {
    return appCopy[language].common.unsetCategory;
  }

  const labels = localizedCategoryLabels[language] as Record<string, string>;

  return labels[category] ?? category;
}

export const billingCycleLabels = {
  en: {
    monthly: "Monthly",
    weekly: "Weekly",
    yearly: "Yearly",
  },
  ja: {
    monthly: "月額",
    weekly: "週額",
    yearly: "年額",
  },
  ko: {
    monthly: "월간",
    weekly: "주간",
    yearly: "연간",
  },
  zh: {
    monthly: "月付",
    weekly: "周付",
    yearly: "年付",
  },
} as const satisfies Record<LanguageCode, Record<BillingCycle, string>>;

export function getBillingCycleLabel(
  billingCycle: BillingCycleValue,
  language: LanguageCode,
): string {
  if (!billingCycle) {
    return appCopy[language].common.unsetBillingCycle;
  }

  return billingCycleLabels[language][billingCycle];
}

export const navigationLabels = {
  en: {
    Add: "Add",
    Home: "Home",
    Setting: "Settings",
    Stats: "Stats",
  },
  ja: {
    Add: "追加",
    Home: "ホーム",
    Setting: "設定",
    Stats: "課金額",
  },
  ko: {
    Add: "추가",
    Home: "홈",
    Setting: "설정",
    Stats: "결제금액",
  },
  zh: {
    Add: "添加",
    Home: "首页",
    Setting: "设置",
    Stats: "费用",
  },
} as const satisfies Record<
  LanguageCode,
  Record<"Home" | "Add" | "Stats" | "Setting", string>
>;

export const appCopy = {
  en: {
    add: {
      categoryLabel: "Category",
      categoryPlaceholder: "Select a category",
      cycleLabel: "Billing Cycle",
      description: "Saved in SQLite and kept even after the app is closed.",
      eyebrow: "Add Subscription",
      memoLabel: "Memo",
      memoPlaceholder: "Add a note if needed",
      nextPaymentDateLabel: "Next Payment Date",
      priceLabel: "Price (JPY)",
      pricePlaceholder: "Example: 1280",
      resetConfirmMessage:
        "Do you want to reset the current input?\nAnything you have entered will be removed.",
      resetConfirmTitle: "Reset the form?",
      saveFailed: "Failed to save.",
      submittingButton: "Saving...",
      submitButton: "Save",
      success: "Saved.",
      title: "Add a new subscription",
      nameLabel: "Service Name",
      namePlaceholder: "Example: YouTube Premium",
    },
    common: {
      active: "Active",
      back: "Back",
      cancel: "Cancel",
      clear: "Clear",
      delete: "Delete",
      edit: "Edit",
      home: "Home",
      inactive: "Inactive",
      loading: "Loading...",
      noMoreInput: "You cannot enter more characters",
      notEntered: "Not entered",
      ok: "OK",
      reset: "Reset",
      selectPaymentDate: "Select payment date",
      unsetBillingCycle: "Billing cycle not set",
      unsetCategory: "Category not set",
      unsetPaymentDate: "Payment date not set",
      unsetPrice: "Price not set",
      exchangeRateFallback:
        "Failed to fetch exchange rates. Prices will be shown in JPY.",
      exchangeRateApproximate:
        "Exchange rates could not be fetched, so approximate rates are being used.",
      remainingCharacters: (count: number) => `${count} characters left`,
      saveFailed: "Failed to save.",
      validation: {
        billingCycleRequired: "Please select a billing cycle.",
        categoryRequired: "Please select a category.",
        memoTooLong: "Memo must be 100 characters or fewer.",
        notificationEmailInvalid:
          "Please enter a valid notification email address.",
        nextPaymentDateInvalid: "Next payment date must be in YYYY-MM-DD format.",
        nextPaymentDateRequired: "Next payment date is required.",
        priceRequired: "Price is required.",
        priceTooLow: "Price must be 1 or greater.",
        serviceNameRequired: "Service name is required.",
      },
      unsupportedAlert: "Not supported right now.",
    },
    detail: {
      createdAt: "Created At",
      deleteConfirmMessage:
        "Once deleted, this cannot be restored.\nDo you want to delete it?",
      deleteConfirmTitle: "Delete",
      deleteButton: "Delete",
      description:
        "Review the saved details and update or delete them when needed.",
      categoryLabel: "Category",
      cycleLabel: "Billing Cycle",
      editButton: "Edit",
      eyebrow: "Subscription Detail",
      memoLabel: "Memo",
      missingTitle: "Subscription not found",
      nameLabel: "Service Name",
      nextPaymentDateLabel: "Next Payment Date",
      priceLabel: "Price (JPY)",
      statusLabel: "Status",
      titleFallback: "Subscription Detail",
      updatedAt: "Updated At",
    },
    edit: {
      cancelButton: "Cancel",
      categoryLabel: "Category",
      categoryPlaceholder: "Select a category",
      cycleLabel: "Billing Cycle",
      description:
        "Review the current values and update only the fields you need.",
      eyebrow: "Edit Subscription",
      memoLabel: "Memo",
      memoPlaceholder: "Add a note if needed",
      missingTitle: "Subscription not found",
      nextPaymentDateLabel: "Next Payment Date",
      priceLabel: "Price (JPY)",
      pricePlaceholder: "Example: 1280",
      saveButton: "Save",
      saveFailed: "Failed to save.",
      savingButton: "Saving...",
      success: "Updated.",
      title: "Edit subscription details",
      toHome: "Back to Home",
      nameLabel: "Service Name",
      namePlaceholder: "Example: YouTube Premium",
    },
    home: {
      annualHelper: "Annual estimate",
      annualLabel: "Annual Total",
      categoryTitle: "Category",
      deleteConfirmMessage:
        "Once deleted, this cannot be restored.\nDo you want to delete it?",
      deleteConfirmTitle: "Delete",
      emptyDescription:
        "No subscriptions are registered yet.\nPlease add one from the Add screen.",
      emptyTitle: "No subscriptions registered",
      itemCount: (count: number) => `${count} items`,
      monthlyHelper: "Monthly normalized",
      monthlyLabel: "This Month",
      displayModes: {
        compactGrid: "Compact Grid",
        compactList: "Compact List",
        normalGrid: "Grid",
        normalList: "List",
      },
      sectionTitle: "Active subscriptions",
      sortOptions: {
        newest: "Newest",
        oldest: "Oldest",
        paymentDate: "Payment Date",
      },
      sortTitle: "Sort",
      toggleConfirmActive:
        "Is it okay to enable this?\nYou can disable it again anytime.",
      toggleConfirmInactive:
        "Is it okay to disable this?\nYou can enable it again anytime.",
      toggleConfirmTitle: "Confirm",
    },
    settings: {
      appInfoDescription: "Version and support information.",
      appInfoLabel: "App Info",
      appVersion: "v1.0.0",
      backupDescription: "Backup configuration is not available yet.",
      backupLabel: "Data Backup",
      basicSection: "Settings",
      currencyDescription: "Select one of CNY, JPY, KRW, or USD.",
      currencyLabel: "Currency",
      darkModeDescription: "Switch between light mode and dark mode.",
      darkModeLabel: "Dark Mode",
      heroDescription:
        "Display and language preferences are saved locally on this device.",
      heroEyebrow: "Settings",
      heroTitle: "Settings",
      notificationEmailDescription:
        "Register the email address that will receive payment reminders.",
      notificationEmailChangeButton: "Change Address",
      notificationEmailChangeConfirmMessage:
        "Is it okay to change the address?",
      notificationEmailEmptyState: "Enter your email address",
      notificationEmailLabel: "Notification Email",
      notificationEmailPlaceholder: "example@example.com",
      notificationEmailSave: "Save Email",
      notificationEmailSaved: "Notification email saved.",
      notificationEmailUnset: "Not set",
      languageDescription:
        "Select Chinese, English, Japanese, or Korean.",
      languageLabel: "Language",
      languageValue: {
        en: "English",
        ja: "日本語",
        ko: "한국어",
        zh: "中文",
      },
      notificationDisableConfirmMessage:
        "Turn notifications off?\nThe day-before-payment email reminder will not be sent.",
      notificationEnableConfirmMessage:
        "Turn notifications on?\nA reminder will be sent to the registered email address the day before payment.",
      notificationEmailMissingWarning:
        "Notifications are on, but no email address is registered yet.",
      notificationOffHint: "Notifications are currently turned off.",
      notificationDescription:
        "Payment reminder emails are managed through the backend API.",
      notificationLabel: "Notifications",
      unsupported: "Not supported",
      unsupportedAlert: "Not supported right now.",
    },
    stats: {
      annualHelper: "12-month view",
      annualLabel: "Annual Estimate",
      description:
        "Shows normalized monthly totals and simple category-based bars.",
      eyebrow: "Insights",
      monthlyHelper: "Current recurring cost",
      monthlyLabel: "Monthly Total",
      sectionTitle: "By Category",
      title: "Track category spending",
    },
    subscriptionCard: {
      deleteButton: "Delete",
      editButton: "Edit",
      endingLabel: (date: string) => `Ends on next payment: ${date}`,
      memoPrefix: "Memo",
      nextPaymentLabel: (date: string) => `Next payment: ${date}`,
    },
  },
  ja: {
    add: {
      categoryLabel: "カテゴリ",
      categoryPlaceholder: "カテゴリを選択",
      cycleLabel: "支払い周期",
      description: "アプリを閉じたあとも内容を保持します。",
      eyebrow: "Add Subscription",
      memoLabel: "メモ",
      memoPlaceholder: "メモがあれば入力",
      nextPaymentDateLabel: "次回支払日",
      priceLabel: "料金（日本円）",
      pricePlaceholder: "例: 1280",
      resetConfirmMessage:
        "入力内容をリセットしますか？\n現在入力中の内容は削除されます。",
      resetConfirmTitle: "入力内容をリセットしますか？",
      saveFailed: "保存に失敗しました。",
      submittingButton: "保存中...",
      submitButton: "登録する",
      success: "登録しました",
      title: "新しい支払いを登録",
      nameLabel: "サービス名",
      namePlaceholder: "例: YouTube Premium",
    },
    common: {
      active: "有効",
      back: "戻る",
      cancel: "キャンセル",
      clear: "クリア",
      delete: "削除",
      edit: "修正",
      home: "ホーム",
      inactive: "無効",
      loading: "読み込み中...",
      noMoreInput: "これ以上入力できません",
      notEntered: "未入力",
      ok: "OK",
      reset: "リセット",
      selectPaymentDate: "支払日を選択",
      unsetBillingCycle: "支払い周期未設定",
      unsetCategory: "カテゴリ未設定",
      unsetPaymentDate: "支払日未設定",
      unsetPrice: "料金未設定",
      exchangeRateFallback:
        "為替レートの取得に失敗しました。料金は日本円で表示します。",
      exchangeRateApproximate:
        "為替レートを取得できなかったため、概算レートで表示しています。",
      remainingCharacters: (count: number) => `残り${count}文字`,
      saveFailed: "保存に失敗しました。",
      validation: {
        billingCycleRequired: "支払い周期を選択してください。",
        categoryRequired: "カテゴリを選択してください。",
        memoTooLong: "メモは100文字以内で入力してください。",
        notificationEmailInvalid:
          "通知先メールアドレスを正しく入力してください。",
        nextPaymentDateInvalid:
          "次回支払日は YYYY-MM-DD 形式で入力してください。",
        nextPaymentDateRequired: "次回支払日を入力してください。",
        priceRequired: "料金を入力してください。",
        priceTooLow: "料金は1以上で入力してください。",
        serviceNameRequired: "サービス名を入力してください。",
      },
      unsupportedAlert: "現在対応していません。",
    },
    detail: {
      categoryLabel: "カテゴリ",
      createdAt: "作成日時",
      cycleLabel: "支払い周期",
      deleteConfirmMessage:
        "一度削除すると戻せなくなります。\n本当に削除していいですか？",
      deleteConfirmTitle: "削除確認",
      deleteButton: "削除する",
      description:
        "登録済みの内容を確認し、必要に応じて修正や削除ができます。",
      editButton: "修正する",
      eyebrow: "Subscription Detail",
      memoLabel: "メモ",
      missingTitle: "対象のサブスクが見つかりません",
      nameLabel: "サービス名",
      nextPaymentDateLabel: "次回支払日",
      priceLabel: "料金（日本円）",
      statusLabel: "状態",
      titleFallback: "サブスク詳細",
      updatedAt: "更新日時",
    },
    edit: {
      cancelButton: "キャンセル",
      categoryLabel: "カテゴリ",
      categoryPlaceholder: "カテゴリを選択",
      cycleLabel: "支払い周期",
      description:
        "現在の内容を確認しながら、必要な項目だけ更新できます。",
      eyebrow: "Edit Subscription",
      memoLabel: "メモ",
      memoPlaceholder: "メモがあれば入力",
      missingTitle: "対象のサブスクが見つかりません",
      nextPaymentDateLabel: "次回支払日",
      priceLabel: "料金（日本円）",
      pricePlaceholder: "例: 1280",
      saveButton: "保存する",
      saveFailed: "保存に失敗しました。",
      savingButton: "保存中...",
      success: "更新しました",
      title: "サブスク情報を修正",
      toHome: "Homeへ戻る",
      nameLabel: "サービス名",
      namePlaceholder: "例: YouTube Premium",
    },
    home: {
      annualHelper: "年間コスト",
      annualLabel: "年間換算",
      categoryTitle: "カテゴリ",
      deleteConfirmMessage:
        "一度削除すると戻せなくなります。\n本当に削除していいですか？",
      deleteConfirmTitle: "削除確認",
      emptyDescription:
        "まだサブスクが登録されていません。\n追加画面から登録してください。",
      emptyTitle: "サブスク0件",
      itemCount: (count: number) => `${count}件`,
      monthlyHelper: "月額換算",
      monthlyLabel: "今月の支払い",
      displayModes: {
        compactGrid: "簡潔2列",
        compactList: "簡潔1列",
        normalGrid: "通常2列",
        normalList: "通常1列",
      },
      sectionTitle: "サブスク一覧",
      sortOptions: {
        newest: "新しい順",
        oldest: "古い順",
        paymentDate: "支払日順",
      },
      sortTitle: "並び替え",
      toggleConfirmActive:
        "有効にしても問題ないですか？\n※いつでも無効へ戻せます。",
      toggleConfirmInactive:
        "無効にしても問題ないですか？\n※いつでも有効へ戻せます。",
      toggleConfirmTitle: "確認",
    },
    settings: {
      appInfoDescription: "バージョンとサポート情報を表示します。",
      appInfoLabel: "アプリ情報",
      appVersion: "v1.0.0",
      backupDescription: "バックアップ設定はまだ利用できません。",
      backupLabel: "データバックアップ",
      basicSection: "設定",
      currencyDescription: "CNY / JPY / KRW / USD から選択できます。",
      currencyLabel: "通貨",
      darkModeDescription: "ライトモード / ダークモードを切り替えます。",
      darkModeLabel: "ダークモード",
      heroDescription:
        "表示や言語の設定はこの端末に保存されます。",
      heroEyebrow: "設定",
      heroTitle: "設定",
      notificationEmailDescription:
        "支払い前日の通知を受け取るメールアドレスを登録します。",
      notificationEmailChangeButton: "アドレスを変更",
      notificationEmailChangeConfirmMessage:
        "アドレスを変更しますが問題ないですか？",
      notificationEmailEmptyState: "メールアドレスを入力",
      notificationEmailLabel: "通知先メールアドレス",
      notificationEmailPlaceholder: "example@example.com",
      notificationEmailSave: "メールを保存",
      notificationEmailSaved: "通知先メールアドレスを保存しました。",
      notificationEmailUnset: "未設定",
      languageDescription:
        "Chinese / English / Japanese / Korean から選択できます。",
      languageLabel: "言語",
      languageValue: {
        en: "English",
        ja: "日本語",
        ko: "한국어",
        zh: "中文",
      },
      notificationDisableConfirmMessage:
        "通知をOFFにしますか？\n支払い前日のメール通知は送信されません。",
      notificationEnableConfirmMessage:
        "通知をONにしますか？\n支払い前日に登録メールアドレスへ通知します。",
      notificationEmailMissingWarning:
        "通知はONですが、通知先メールアドレスがまだ未入力です。",
      notificationOffHint: "通知は現在OFFです。",
      notificationDescription:
        "登録のアドレス宛に送信されます。",
      notificationLabel: "通知設定",
      unsupported: "未対応",
      unsupportedAlert: "現在対応していません。",
    },
    stats: {
      annualHelper: "12か月換算",
      annualLabel: "年間見込み",
      description:
        "月額換算の合計とカテゴリの比率を簡易バーで表示します。",
      eyebrow: "Insights",
      monthlyHelper: "今月の固定費",
      monthlyLabel: "月額合計",
      sectionTitle: "カテゴリ別",
      title: "カテゴリ別の支出を確認",
    },
    subscriptionCard: {
      deleteButton: "削除",
      editButton: "修正",
      endingLabel: (date: string) => `次回支払いで終了：${date}`,
      memoPrefix: "メモ",
      nextPaymentLabel: (date: string) => `次回支払日：${date}`,
    },
  },
  ko: {
    add: {
      categoryLabel: "카테고리",
      categoryPlaceholder: "카테고리를 선택하세요",
      cycleLabel: "결제 주기",
      description: "SQLite에 저장되며 앱을 종료한 뒤에도 유지됩니다.",
      eyebrow: "Add Subscription",
      memoLabel: "메모",
      memoPlaceholder: "메모가 있으면 입력하세요",
      nextPaymentDateLabel: "다음 결제일",
      priceLabel: "요금(일본 엔)",
      pricePlaceholder: "예: 1280",
      resetConfirmMessage:
        "입력 내용을 초기화할까요?\n현재 입력 중인 내용은 삭제됩니다.",
      resetConfirmTitle: "입력 내용을 초기화할까요?",
      saveFailed: "저장에 실패했습니다.",
      submittingButton: "저장 중...",
      submitButton: "등록하기",
      success: "등록했습니다",
      title: "새 구독을 등록",
      nameLabel: "서비스명",
      namePlaceholder: "예: YouTube Premium",
    },
    common: {
      active: "활성",
      back: "뒤로",
      cancel: "취소",
      clear: "지우기",
      delete: "삭제",
      edit: "수정",
      home: "홈",
      inactive: "비활성",
      loading: "불러오는 중...",
      noMoreInput: "더 이상 입력할 수 없습니다",
      notEntered: "미입력",
      ok: "OK",
      reset: "초기화",
      selectPaymentDate: "결제일 선택",
      unsetBillingCycle: "결제 주기 미설정",
      unsetCategory: "카테고리 미설정",
      unsetPaymentDate: "결제일 미설정",
      unsetPrice: "요금 미설정",
      exchangeRateFallback:
        "환율을 불러오지 못했습니다. 금액은 JPY로 표시합니다.",
      exchangeRateApproximate:
        "환율을 가져오지 못해 대략적인 환율로 표시하고 있습니다.",
      remainingCharacters: (count: number) => `${count}자 남음`,
      saveFailed: "저장에 실패했습니다.",
      validation: {
        billingCycleRequired: "결제 주기를 선택해주세요.",
        categoryRequired: "카테고리를 선택해주세요.",
        memoTooLong: "메모는 100자 이내로 입력해주세요.",
        notificationEmailInvalid:
          "알림을 받을 이메일 주소를 올바르게 입력해주세요.",
        nextPaymentDateInvalid:
          "다음 결제일은 YYYY-MM-DD 형식으로 입력해주세요.",
        nextPaymentDateRequired: "다음 결제일을 입력해주세요.",
        priceRequired: "요금을 입력해주세요.",
        priceTooLow: "요금은 1 이상으로 입력해주세요.",
        serviceNameRequired: "서비스명을 입력해주세요.",
      },
      unsupportedAlert: "현재 지원하지 않습니다.",
    },
    detail: {
      categoryLabel: "카테고리",
      createdAt: "생성일시",
      cycleLabel: "결제 주기",
      deleteConfirmMessage:
        "한 번 삭제하면 되돌릴 수 없습니다.\n정말 삭제하시겠습니까?",
      deleteConfirmTitle: "삭제 확인",
      deleteButton: "삭제하기",
      description: "저장된 내용을 확인하고 필요하면 수정하거나 삭제할 수 있습니다.",
      editButton: "수정하기",
      eyebrow: "Subscription Detail",
      memoLabel: "메모",
      missingTitle: "대상 구독을 찾을 수 없습니다",
      nameLabel: "서비스명",
      nextPaymentDateLabel: "다음 결제일",
      priceLabel: "요금(일본 엔)",
      statusLabel: "상태",
      titleFallback: "구독 상세",
      updatedAt: "수정일시",
    },
    edit: {
      cancelButton: "취소",
      categoryLabel: "카테고리",
      categoryPlaceholder: "카테고리를 선택하세요",
      cycleLabel: "결제 주기",
      description: "현재 내용을 확인하면서 필요한 항목만 수정할 수 있습니다.",
      eyebrow: "Edit Subscription",
      memoLabel: "메모",
      memoPlaceholder: "메모가 있으면 입력하세요",
      missingTitle: "대상 구독을 찾을 수 없습니다",
      nextPaymentDateLabel: "다음 결제일",
      priceLabel: "요금(일본 엔)",
      pricePlaceholder: "예: 1280",
      saveButton: "저장하기",
      saveFailed: "저장에 실패했습니다.",
      savingButton: "저장 중...",
      success: "수정했습니다",
      title: "구독 정보를 수정",
      toHome: "홈으로 돌아가기",
      nameLabel: "서비스명",
      namePlaceholder: "예: YouTube Premium",
    },
    home: {
      annualHelper: "연간 비용",
      annualLabel: "연간 환산",
      categoryTitle: "카테고리",
      deleteConfirmMessage:
        "한 번 삭제하면 되돌릴 수 없습니다.\n정말 삭제하시겠습니까?",
      deleteConfirmTitle: "삭제 확인",
      emptyDescription:
        "아직 구독이 등록되어 있지 않습니다.\n추가 화면에서 등록해주세요.",
      emptyTitle: "구독 0개",
      itemCount: (count: number) => `${count}개`,
      monthlyHelper: "월 환산",
      monthlyLabel: "이번 달 결제",
      displayModes: {
        compactGrid: "간단 2열",
        compactList: "간단 1열",
        normalGrid: "일반 2열",
        normalList: "일반 1열",
      },
      sectionTitle: "등록된 구독",
      sortOptions: {
        newest: "최신순",
        oldest: "오래된순",
        paymentDate: "결제일순",
      },
      sortTitle: "정렬",
      toggleConfirmActive:
        "활성으로 변경해도 괜찮습니까?\n언제든지 다시 비활성으로 바꿀 수 있습니다.",
      toggleConfirmInactive:
        "비활성으로 변경해도 괜찮습니까?\n언제든지 다시 활성으로 바꿀 수 있습니다.",
      toggleConfirmTitle: "확인",
    },
    settings: {
      appInfoDescription: "버전과 지원 정보를 표시합니다.",
      appInfoLabel: "앱 정보",
      appVersion: "v1.0.0",
      backupDescription: "백업 설정은 아직 사용할 수 없습니다.",
      backupLabel: "데이터 백업",
      basicSection: "설정",
      currencyDescription: "CNY / JPY / KRW / USD 중에서 선택합니다.",
      currencyLabel: "통화",
      darkModeDescription: "라이트 모드 / 다크 모드를 전환합니다.",
      darkModeLabel: "다크 모드",
      heroDescription: "표시와 언어 설정은 이 기기에 로컬 저장됩니다.",
      heroEyebrow: "설정",
      heroTitle: "설정",
      notificationEmailDescription:
        "결제 하루 전 알림을 받을 이메일 주소를 등록합니다.",
      notificationEmailChangeButton: "주소 변경",
      notificationEmailChangeConfirmMessage:
        "주소를 변경해도 괜찮습니까?",
      notificationEmailEmptyState: "이메일 주소를 입력하세요",
      notificationEmailLabel: "알림 이메일 주소",
      notificationEmailPlaceholder: "example@example.com",
      notificationEmailSave: "이메일 저장",
      notificationEmailSaved: "알림 이메일 주소를 저장했습니다.",
      notificationEmailUnset: "미설정",
      languageDescription:
        "Chinese / English / Japanese / Korean 중에서 선택합니다.",
      languageLabel: "언어",
      languageValue: {
        en: "English",
        ja: "日本語",
        ko: "한국어",
        zh: "中文",
      },
      notificationDisableConfirmMessage:
        "알림을 OFF로 전환할까요?\n결제 전날 이메일 알림은 발송되지 않습니다.",
      notificationEnableConfirmMessage:
        "알림을 ON으로 전환할까요?\n결제 전날 등록된 이메일 주소로 알림을 보냅니다.",
      notificationEmailMissingWarning:
        "알림은 ON이지만 알림 이메일 주소가 아직 비어 있습니다.",
      notificationOffHint: "알림은 현재 OFF입니다.",
      notificationDescription:
        "결제 알림 이메일은 백엔드 API를 통해 전송됩니다.",
      notificationLabel: "알림 설정",
      unsupported: "미지원",
      unsupportedAlert: "현재 지원하지 않습니다.",
    },
    stats: {
      annualHelper: "12개월 환산",
      annualLabel: "연간 예상",
      description: "월 환산 합계와 카테고리 비율을 간단한 바로 표시합니다.",
      eyebrow: "Insights",
      monthlyHelper: "이번 달 고정비",
      monthlyLabel: "월 합계",
      sectionTitle: "카테고리별",
      title: "카테고리별 지출 확인",
    },
    subscriptionCard: {
      deleteButton: "삭제",
      editButton: "수정",
      endingLabel: (date: string) => `다음 결제 후 종료: ${date}`,
      memoPrefix: "메모",
      nextPaymentLabel: (date: string) => `다음 결제일: ${date}`,
    },
  },
  zh: {
    add: {
      categoryLabel: "类别",
      categoryPlaceholder: "请选择类别",
      cycleLabel: "支付周期",
      description: "数据会保存在 SQLite 中，关闭应用后也会保留。",
      eyebrow: "Add Subscription",
      memoLabel: "备注",
      memoPlaceholder: "如有备注可填写",
      nextPaymentDateLabel: "下次支付日",
      priceLabel: "价格（日元）",
      pricePlaceholder: "例如: 1280",
      resetConfirmMessage:
        "要重置当前输入内容吗？\n正在输入的内容将被删除。",
      resetConfirmTitle: "要重置输入内容吗？",
      saveFailed: "保存失败。",
      submittingButton: "保存中...",
      submitButton: "添加",
      success: "已添加。",
      title: "添加新的订阅",
      nameLabel: "服务名称",
      namePlaceholder: "例如: YouTube Premium",
    },
    common: {
      active: "启用",
      back: "返回",
      cancel: "取消",
      clear: "清除",
      delete: "删除",
      edit: "修改",
      home: "首页",
      inactive: "停用",
      loading: "加载中...",
      noMoreInput: "无法继续输入",
      notEntered: "未填写",
      ok: "确定",
      reset: "重置",
      selectPaymentDate: "选择支付日",
      unsetBillingCycle: "支付周期未设置",
      unsetCategory: "类别未设置",
      unsetPaymentDate: "支付日未设置",
      unsetPrice: "价格未设置",
      exchangeRateFallback:
        "获取汇率失败。金额将以日元显示。",
      exchangeRateApproximate:
        "由于无法获取汇率，当前使用概算汇率显示。",
      remainingCharacters: (count: number) => `剩余${count}个字符`,
      saveFailed: "保存失败。",
      validation: {
        billingCycleRequired: "请选择支付周期。",
        categoryRequired: "请选择类别。",
        memoTooLong: "备注不能超过 100 个字符。",
        notificationEmailInvalid: "请输入正确的通知邮箱地址。",
        nextPaymentDateInvalid: "下次支付日必须为 YYYY-MM-DD 格式。",
        nextPaymentDateRequired: "请输入下次支付日。",
        priceRequired: "请输入价格。",
        priceTooLow: "价格必须大于等于 1。",
        serviceNameRequired: "请输入服务名称。",
      },
      unsupportedAlert: "暂不支持。",
    },
    detail: {
      categoryLabel: "类别",
      createdAt: "创建时间",
      cycleLabel: "支付周期",
      deleteConfirmMessage:
        "删除后将无法恢复。\n确定要删除吗？",
      deleteConfirmTitle: "删除确认",
      deleteButton: "删除",
      description: "可以查看已保存内容，并按需修改或删除。",
      editButton: "修改",
      eyebrow: "Subscription Detail",
      memoLabel: "备注",
      missingTitle: "未找到对应订阅",
      nameLabel: "服务名称",
      nextPaymentDateLabel: "下次支付日",
      priceLabel: "价格（日元）",
      statusLabel: "状态",
      titleFallback: "订阅详情",
      updatedAt: "更新时间",
    },
    edit: {
      cancelButton: "取消",
      categoryLabel: "类别",
      categoryPlaceholder: "请选择类别",
      cycleLabel: "支付周期",
      description: "确认当前内容后，只修改需要变更的项目。",
      eyebrow: "Edit Subscription",
      memoLabel: "备注",
      memoPlaceholder: "如有备注可填写",
      missingTitle: "未找到对应订阅",
      nextPaymentDateLabel: "下次支付日",
      priceLabel: "价格（日元）",
      pricePlaceholder: "例如: 1280",
      saveButton: "保存",
      saveFailed: "保存失败。",
      savingButton: "保存中...",
      success: "已更新。",
      title: "修改订阅信息",
      toHome: "返回首页",
      nameLabel: "服务名称",
      namePlaceholder: "例如: YouTube Premium",
    },
    home: {
      annualHelper: "年度费用",
      annualLabel: "年度换算",
      categoryTitle: "类别",
      deleteConfirmMessage:
        "删除后将无法恢复。\n确定要删除吗？",
      deleteConfirmTitle: "删除确认",
      emptyDescription:
        "还没有注册任何订阅。\n请从添加页面进行添加。",
      emptyTitle: "订阅 0 项",
      itemCount: (count: number) => `${count}项`,
      monthlyHelper: "月度换算",
      monthlyLabel: "本月支出",
      displayModes: {
        compactGrid: "简洁2列",
        compactList: "简洁1列",
        normalGrid: "普通2列",
        normalList: "普通1列",
      },
      sectionTitle: "已注册的订阅",
      sortOptions: {
        newest: "最新顺序",
        oldest: "最早顺序",
        paymentDate: "支付日顺序",
      },
      sortTitle: "排序",
      toggleConfirmActive:
        "确定要启用吗？\n之后也可以随时停用。",
      toggleConfirmInactive:
        "确定要停用吗？\n之后也可以随时重新启用。",
      toggleConfirmTitle: "确认",
    },
    settings: {
      appInfoDescription: "显示版本和支持信息。",
      appInfoLabel: "应用信息",
      appVersion: "v1.0.0",
      backupDescription: "备份功能暂不可用。",
      backupLabel: "数据备份",
      basicSection: "设置",
      currencyDescription: "可从 CNY / JPY / KRW / USD 中选择。",
      currencyLabel: "货币",
      darkModeDescription: "切换浅色模式和深色模式。",
      darkModeLabel: "深色模式",
      heroDescription: "显示、语言和通知邮箱设置会保存在本机。",
      heroEyebrow: "设置",
      heroTitle: "设置",
      languageDescription: "可选择 Chinese / English / Japanese / Korean。",
      languageLabel: "语言",
      languageValue: {
        en: "English",
        ja: "日本語",
        ko: "한국어",
        zh: "中文",
      },
      notificationDisableConfirmMessage:
        "要关闭通知吗？\n支付前一天的邮件提醒将不会发送。",
      notificationEnableConfirmMessage:
        "要开启通知吗？\n将在支付前一天向已登记邮箱发送提醒。",
      notificationEmailMissingWarning:
        "通知已开启，但通知邮箱地址仍未填写。",
      notificationOffHint: "通知当前为关闭状态。",
      notificationDescription: "支付提醒邮件将通过后端 API 发送。",
      notificationLabel: "通知设置",
      notificationEmailChangeButton: "修改地址",
      notificationEmailChangeConfirmMessage:
        "修改地址也没问题吗？",
      notificationEmailEmptyState: "请输入邮箱地址",
      notificationEmailDescription:
        "登记用于接收支付前一天提醒的邮箱地址。",
      notificationEmailLabel: "通知邮箱地址",
      notificationEmailPlaceholder: "example@example.com",
      notificationEmailSave: "保存邮箱",
      notificationEmailSaved: "通知邮箱地址已保存。",
      notificationEmailUnset: "未设置",
      unsupported: "未支持",
      unsupportedAlert: "暂不支持。",
    },
    stats: {
      annualHelper: "12 个月换算",
      annualLabel: "年度预计",
      description: "以月度换算总额和简易柱状图显示各类别支出。",
      eyebrow: "Insights",
      monthlyHelper: "本月固定支出",
      monthlyLabel: "月度合计",
      sectionTitle: "按类别",
      title: "查看各类别支出",
    },
    subscriptionCard: {
      deleteButton: "删除",
      editButton: "修改",
      endingLabel: (date: string) => `将在下次支付后结束：${date}`,
      memoPrefix: "备注",
      nextPaymentLabel: (date: string) => `下次支付日：${date}`,
    },
  },
} as const;

export const settingsCopy = {
  en: appCopy.en.settings,
  ja: appCopy.ja.settings,
  ko: appCopy.ko.settings,
  zh: appCopy.zh.settings,
} as const;
